# Site settings
title: 'Benjamin Knight, Designer & Developer'
email: ben@benknight.me
description: Front end designer & developer. I've got moxie!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://benknight.github.io" # the base hostname & protocol for your site
collections:
- projects


# Build settings
markdown: kramdown
sass:
  style: :compressed
